### PR TITLE
Provide SSL security policy

### PR DESCRIPTION
**Pull request by richardj-bsquare**
## what

Fixes the following error:

* aws_elastic_beanstalk_environment.default: Error waiting for Elastic Beanstalk Environment (e-kiusnj9mi2) to become ready: 2 errors occurred:
	* 2019-05-10 12:08:15.882 +0000 UTC (e-kiusnj9mi2) : Stack named 'awseb-e-kiusnj9mi2-stack' aborted operation. Current state: 'CREATE_FAILED'  Reason: The following resource(s) failed to create: [AWSEBV2LoadBalancerListener443]. 
	* 2019-05-10 12:08:15.983 +0000 UTC (e-kiusnj9mi2) : Creating Load Balancer listener failed Reason: An SSL policy must be specified for HTTPS listeners (Service: AmazonElasticLoadBalancingV2; Status Code: 400; Error Code: ValidationError; Request ID: 43157996-731c-11e9-891f-117f22424633)

Which has been reported as an issue on the upstream project: https://github.com/cloudposse/terraform-aws-elastic-beanstalk-environment/issues/81

## references
- Closes https://github.com/cloudposse/terraform-aws-jenkins/issues/46

### CODE REVIEW

**Comment by richardj-bsquare** [comment]
Addresses https://github.com/cloudposse/terraform-aws-jenkins/issues/46

**Review by aknysh — DISMISSED** [review]
thanks @richardj-bsquare 

Looks good, but please rebuild README by executing these commands:

```
make init
make readme/deps
make readme
```

It will add the new variables and outputs to `README.md` automatically.

In general, any changes to README should be made in `README.yaml` (not in this case), and after that executing the commands above will rebuild `README.yaml` into `README.md` and add all new variables and outputs to `README.md`

thanks

**Comment by richardj-bsquare** [comment]
Review comments addressed.

**Comment by chris-str-cst** [comment]
Can we please merge this fix?

**Comment by chris-str-cst** [comment]
@aknysh Is it now ok?

**Comment by rdelcampog** [comment]
Please, backport to 0.6.0 and upgrade registry.

**Review by nitrocode — APPROVED** [review]

**Comment by nitrocode** [comment]
Thanks for the update @richardj-bsquare ! Sorry for the long wait. I made some updates in order to expose this input to this module.

**Pull request merged**
