### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nodomain**
It just worked with a personal access token for me.

### CODE REVIEW

**Comment by osterman** [comment]
@nodomain - just for clarification, is your `jenkins` repo public?

**Comment by nodomain** [comment]
Yes it is. It did not work with yours either. See @nodomain/jenkins

**Comment by aknysh** [comment]
@nodomain can you address the comments?

**Comment by aknysh** [comment]
closing now
the module was converted to TF 0.12.
GitHub token is a required variable now

**Pull request closed without merging**
